### ISSUE TITLE
Import Slack file attachments

### ISSUE THREAD

**Issue by yugoccp** [yugoccp/slack2discord#2]
Links work fine, but file attachments uploaded at Slack server seem not work.

**Comment by brjavaman** [comment]
Are you having issues with downloading an attachment from Slack, or uploading to Discord?

Here is an example of discord.js on how to attach files in different ways:

https://github.com/discordjs/discord.js/blob/master/docs/examples/attachments.md

**Comment by yugoccp** [comment]
Thanks for the reference @brjavaman! We need to extract the message file URL, download it, and upload it to Discord.
