### ISSUE TITLE
SyntaxError: Unexpected token I in JSON at position 1

### ISSUE THREAD

**Issue by kdmsnr** [yugoccp/slack2discord#20]
It fails at JSON.parse.

```
[INFO] Read Slack XXX channel backup files...
 ^

SyntaxError: Unexpected token I in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.getMessages (/opt/homebrew/lib/node_modules/slack2discord/src/slackService.js:61:15)
    at async /opt/homebrew/lib/node_modules/slack2discord/src/commands/parseMessages.js:27:29
```

**Comment by yugoccp** [comment]
> It fails at JSON.parse.
> 
> ```
> [INFO] Read Slack XXX channel backup files...
>  ^
> 
> SyntaxError: Unexpected token I in JSON at position 1
>     at JSON.parse (<anonymous>)
>     at Object.getMessages (/opt/homebrew/lib/node_modules/slack2discord/src/slackService.js:61:15)
>     at async /opt/homebrew/lib/node_modules/slack2discord/src/commands/parseMessages.js:27:29
> ```

Hi @kdmsnr ! Thanks for trying it! Could you please provide a sample of the message that are failing to parse?

**Comment by nitrousnrg** [comment]
same issue here...

**Comment by yugoccp** [comment]
> same issue here...

Hey @nitrousnrg ! Thanks for using it! Could you please send a sample of the message that is failing to help me fix the issue?

**Comment by stephds01** [comment]
Hello @yougoccp,
To start Thank you for your program ;)
I encounter an error message when I run the program with this line: s2d run -t "Xttttderfderfderfd" -sid "000000000000000"
Here is the error message:

D:\Utilisateurs\Utilisateur\Documents\Transfert Slack\Expatriation Allemagne Slack export Feb 5 2020 - Jul 25 2022>  s2d run -t "Xttttderfderfderfd" -sid "000000000000000"
Parsing messages from D:\Utilisateurs\Utilisateur\Documents\Transfert Slack\Expatriation Allemagne Slack export Feb 5 2020 - Jul 25 2022
(node:33076) ExperimentalWarning: The fs.promises API is experimental
Sending messages from D:\Utilisateurs\Utilisateur\Documents\Transfert Slack\Expatriation Allemagne Slack export Feb 5 2020 - Jul 25 2022/.s2d/out to Discord
(node:33076) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token I in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.getMessages (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\slack2discord\src\slackService.js:61:15)
(node:33076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33076) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at Object.getOrCreateChannel (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\slack2discord\src\discordService.js:32:24)
    at sendToDiscord (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\slack2discord\src\commands\sendMessages.js:46:42)
(node:33076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

Can you help me ?

Thank's for advance

**Comment by yugoccp** [comment]
Hi @kdmsnr @nitrousnrg ! I've upgraded DiscordJS client to latest version, hope it does work for you! Please note that it works on NodeJS 16+!

Thanks for using it!
