### ISSUE TITLE
A problem with the import

### ISSUE THREAD

**Issue by antoniosantosramos** [yugoccp/slack2discord#24]
Hello, I am trying this script and I have this problem when I import.
Do you have any idea?

I am in the root and I have several directories with the json files

![image](https://user-images.githubusercontent.com/20588051/190879313-f0086560-106d-4474-87f6-d5f06384301c.png)

And if I delete all the channel except one of then, this is the error message when I import this channel

![image](https://user-images.githubusercontent.com/20588051/190879460-0fa08fbd-bd49-4268-871d-2643be601c9e.png)

**Comment by yugoccp** [comment]
Hi @antoniosantosramos ! I've just published new version 1.0.6 to support Windows path. Could you please try again?

**Comment by antoniosantosramos** [comment]
Hi @yugoccp 

No works yet. There is a new error

![image](https://user-images.githubusercontent.com/20588051/192598439-f37e3f50-23ad-4f2c-aa1e-f9e8c6601e9e.png)

And if I delete all the channel except one of then, this is the error message when I import this channel

![image](https://user-images.githubusercontent.com/20588051/192598701-e030d442-a7ba-4ce4-a04e-0cd890ca9c58.png)

**Comment by wishx** [comment]
I seem to have this exact issue.

**Comment by yugoccp** [comment]
@antoniosantosramos fixed this issue on version 1.0.8! Please check it out!

Looking forward!
